### ISSUE TITLE
What would you suggest for sfc restart file ?

### ISSUE THREAD

**Issue by manmeet3591** [tmiyachi/data2gfs#1]
I was able to run your data2gfs which generates the sigma restart files. The model runs with the generated files. Now I want to generate the sfc file as well. What would you suggest for that?

**Comment by tmiyachi** [comment]
I don't have any good idea to generate sfc files. I made the model run with avaiable open data sets such as NCEP-CFS reanalysis and NCEP operational forecast (https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/), where I was able to access surface condition files formated as GFS sfc file.

**Comment by manmeet3591** [comment]
@tmiyachi I have been able to work around this. Will post in a few days and request you to merge the changes. I want to thank you for putting this out in the open. It has helped me a lot. Also if you may agree to merge the sfc files generation code as well, I think data2gfs would be complemented by it.

**Comment by tmiyachi** [comment]
@manmeet3591 Thank you for your great work! I would be glad if my code is helpful for you.
